# Classificação binária - Brest Cancer Simples

Base de dados: https://archive.ics.uci.edu/dataset/17/breast+cancer+winsconsin+diagnostic

## Importando base de dados

In [1]:
import pandas as pd

In [2]:
# previsores 
X = pd.read_csv('2_cancer_entradas.csv')
X

radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
0      17.99     10.38      122.80  1001.0      0.11840       0.27760   
1      20.57     17.77      132.90  1326.0      0.08474       0.07864   
2      19.69     21.25      130.00  1203.0      0.10960       0.15990   
3      11.42     20.38       77.58   386.1      0.14250       0.28390   
4      20.29     14.34      135.10  1297.0      0.10030       0.13280   
..       ...       ...         ...     ...          ...           ...   
564    21.56     22.39      142.00  1479.0      0.11100       0.11590   
565    20.13     28.25      131.20  1261.0      0.09780       0.10340   
566    16.60     28.08      108.30   858.1      0.08455       0.10230   
567    20.60     29.33      140.10  1265.0      0.11780       0.27700   
568     7.76     24.54       47.92   181.0      0.05263       0.04362   

     concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
0       0.30010          0.14710     0.2419             0.07871  ...   25.380   
1       0.08690          0.07017     0.1812             0.05667  ...   24.990   
2       0.19740          0.12790     0.2069             0.05999  ...   23.570   
3       0.24140          0.10520     0.2597             0.09744  ...   14.910   
4       0.19800          0.10430     0.1809             0.05883  ...   22.540   
..          ...              ...        ...                 ...  ...      ...   
564     0.24390          0.13890     0.1726             0.05623  ...   25.450   
565     0.14400          0.09791     0.1752             0.05533  ...   23.690   
566     0.09251          0.05302     0.1590             0.05648  ...   18.980   
567     0.35140          0.15200     0.2397             0.07016  ...   25.740   
568     0.00000          0.00000     0.1587             0.05884  ...    9.456   

     texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
0       17.33      184.60  2019.0      0.16220       0.66560      0.7119   
1       23.41      158.80  1956.0      0.12380       0.18660      0.2416   
2       25.53      152.50  1709.0      0.14440       0.42450      0.4504   
3       26.50       98.87   567.7      0.20980       0.86630      0.6869   
4       16.67      152.20  1575.0      0.13740       0.20500      0.4000   
..        ...         ...     ...          ...           ...         ...   
564     26.40      166.10  2027.0      0.14100       0.21130      0.4107   
565     38.25      155.00  1731.0      0.11660       0.19220      0.3215   
566     34.12      126.70  1124.0      0.11390       0.30940      0.3403   
567     39.42      184.60  1821.0      0.16500       0.86810      0.9387   
568     30.37       59.16   268.6      0.08996       0.06444      0.0000   

     concave_points3  symmetry3  fractal_dimension3  
0             0.2654     0.4601             0.11890  
1             0.1860     0.2750             0.08902  
2             0.2430     0.3613             0.08758  
3             0.2575     0.6638             0.17300  
4             0.1625     0.2364             0.07678  
..               ...        ...                 ...  
564           0.2216     0.2060             0.07115  
565           0.1628     0.2572             0.06637  
566           0.1418     0.2218             0.07820  
567           0.2650     0.4087             0.12400  
568           0.0000     0.2871             0.07039  

[569 rows x 30 columns]

In [3]:
# saidas 
y = pd.read_csv('2_cancer_saidas.csv')
y

Diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

## Divisão base de treino e teste

In [4]:
import sklearn 
from sklearn.model_selection import train_test_split
sklearn.__version__

'1.4.2'

In [5]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X,y,test_size=0.25)

In [6]:
X_treinamento.shape , y_treinamento.shape

((426, 30), (426, 1))

In [7]:
X_teste.shape , y_teste.shape

((143, 30), (143, 1))

## Tratando a base de dados

In [8]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Converte os rótulos para numérico (0 e 1)
label_encoder = LabelEncoder()
y_treinamento = label_encoder.fit_transform(y_treinamento)
y_teste = label_encoder.fit_transform(y_teste)

# Converte X_treinamento para float32 se ainda não estiver
X_treinamento = np.array(X_treinamento, dtype=np.float32)
y_treinamento = np.array(y_treinamento, dtype=np.float32)
y_teste = np.array(y_teste, dtype=np.float32)

/home/lucas/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/lucas/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Estrutura da Rede Neural

In [9]:
# Importacao desta lib para desativar erro no TensorFlow
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [10]:
# !pip uninstall -y tensorflow
!pip install -q tensorflow==2.16.1
import tensorflow as tf
from tensorflow.keras.models import Sequential
tf.__version__

2025-01-03 14:35:31.823731: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-03 14:35:32.037410: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-03 14:35:32.817581: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-01-03 14:35:34.910859: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


'2.16.1'

In [23]:
# shape - numero de colunas do dataframe
# units - para calcular units, depende da quantidade de colunas (30) e de saidas (1) Pois é uma classificação binária
#
#    (30 + 1) / 2 = 15.5 => 16
#

rede_neural = Sequential([
     tf.keras.layers.InputLayer(shape = (30,)),
     tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
     tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
     tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

In [24]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

## Configuração e execução da rede neural

In [25]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [26]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [27]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - binary_accuracy: 0.6867 - loss: 0.8413
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8778 - loss: 0.3469
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8581 - loss: 0.3098
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9043 - loss: 0.2579
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9233 - loss: 0.2151
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9295 - loss: 0.1990
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9126 - loss: 0.2140
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9088 - loss: 0.2538
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9027 - loss: 0.2606
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9151 - loss: 0.2391
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8874 -

In [29]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-1.83819562e-01,  1.09799102e-01, -2.63468754e-02,
         -3.40849906e-02,  4.74026538e-02, -3.47052887e-02,
          2.07814910e-02,  1.91462874e-01,  2.25485221e-01,
         -3.86696942e-02, -5.46284802e-02, -1.90638471e-02,
          1.54632712e-02,  1.72322057e-02,  2.80417912e-02,
          2.72296369e-04],
        [-4.66661081e-02,  6.06926791e-02,  2.83829868e-05,
         -4.80839387e-02, -2.33134869e-02, -1.89223997e-02,
         -4.27656248e-03,  1.32045940e-01, -5.94955776e-03,
         -4.32725437e-02, -4.62814458e-02, -2.18940452e-02,
          4.63029817e-02,  4.81739752e-02,  2.05656551e-02,
         -3.02688014e-02],
        [ 8.46629813e-02, -3.27948295e-02,  2.77142264e-02,
          4.88540642e-02, -2.31650602e-02,  6.41487166e-02,
         -3.14790495e-02, -1.76703613e-02, -1.03909105e-01,
          3.76166590e-02,  1.87733956e-02,  3.58581208e-02,
         -4.16504256e-02,  3.10174935e-02, -2.11526994e-02,
          2.66409256e-02],
        [ 8.6800195

In [30]:
len(pesos0)

2

In [31]:
len(pesos0[1])

16

In [32]:
len(pesos0[0])

30

In [33]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[ 1.01424769e-01, -1.47756105e-02,  1.80554986e-01,
         -1.87365692e-02, -7.54951313e-02,  2.43881211e-01,
         -8.45389161e-03, -5.52540459e-03,  3.87600690e-01,
         -2.03093607e-02,  9.60952416e-02,  1.92532539e-01,
          9.52359848e-03, -3.89482919e-03, -6.22992730e-03,
         -4.18767333e-02],
        [ 2.18086138e-01,  9.02945399e-02, -5.40521666e-02,
         -5.79433776e-02, -2.57370179e-03,  2.24946246e-01,
         -4.65930328e-02, -5.29972650e-02,  1.82411432e-01,
          7.31574446e-02, -8.22473839e-02, -6.18848018e-02,
         -7.70844817e-02, -5.06316014e-02, -7.43822455e-02,
         -2.57363673e-02],
        [-3.79967317e-02,  2.91116275e-02,  9.69090313e-03,
         -7.76414946e-03,  7.17978552e-03, -2.20245719e-02,
         -4.28601280e-02,  3.37539986e-03, -3.67963798e-02,
          2.30915435e-02, -1.36439316e-02,  4.61995602e-04,
         -1.88749917e-02, -4.39765453e-02,  2.15656273e-02,
          3.10388319e-02],
        [-3.8917742

In [34]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[ 0.26181608],
        [ 0.55785125],
        [-0.34045887],
        [-0.12104701],
        [-0.39876267],
        [ 0.13064355],
        [ 0.04888377],
        [-0.0832195 ],
        [ 0.06230897],
        [ 0.6187933 ],
        [-0.13845032],
        [-0.35410497],
        [-0.07899067],
        [-0.08478231],
        [-0.05285602],
        [ 0.32947809]], dtype=float32),
 array([-0.17227583], dtype=float32)]

## Previsões

In [17]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5 # Convertendo o valor float com uma classe True/False

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step


In [24]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [

In [18]:
y_teste

array([1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 0., 1., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 1.], dtype=float32)

## Comparação da base de previsão com a base de teste

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [20]:
accuracy_score(y_teste, previsoes)

0.8531468531468531

In [21]:
confusion_matrix(y_teste, previsoes)

array([[86,  1],
       [20, 36]])

In [28]:
rede_neural.evaluate(X_teste,y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9017 - loss: 0.3706  


[0.3848976492881775, 0.8951048851013184]

## Validação Cruzada

In [35]:
!pip install scikeras

In [36]:
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

In [37]:
pd.__version__ , tf.__version__, sklearn.__version__, scikeras.__version__

('2.2.2', '2.16.1', '1.4.2', '0.13.0')

In [38]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as k

In [39]:
def criar_rede():
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape = (30,)), 
        tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
        #tf.keras.layers.Dropout(rate = 0.2),# Aqui é a aplicação de um Dropout - não obrigatório para avaliar a rede_neural
        tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
        #tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
    otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)
    rede_neural.compile(optimizer = otimizador, loss='binary_crossentropy', metrics = ['binary_accuracy'])
    return rede_neural

In [40]:
rede_neural = KerasClassifier(model = criar_rede, epochs=100, batch_size=10)

In [41]:
resultados = cross_val_score(estimator = rede_neural, X = X , y = y, cv = 10, scoring = 'accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - binary_accuracy: 0.5939 - loss: 0.9237
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8542 - loss: 0.4421
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8883 - loss: 0.3243
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9327 - loss: 0.2381
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8898 - loss: 0.2921
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.8994 - loss: 0.2535
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.8970 - loss: 0.2502
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.9026 - loss: 0.2655
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9117 - loss: 0.2293
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9288 - loss: 0.1731
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8836 -

In [42]:
# Sem Dropout
resultados

array([0.92982456, 0.96491228, 0.89473684, 0.94736842, 0.84210526,
       0.8245614 , 0.89473684, 0.89473684, 0.94736842, 0.80357143])

In [43]:
# Sem Dropout
resultados.mean()

0.8943922305764411

In [44]:
# Sem Dropout
resultados.std()

0.052631289905519706

In [40]:
# Com Dropout
resultados

array([0.9122807 , 0.92982456, 0.9122807 , 0.94736842, 0.94736842,
       0.89473684, 0.96491228, 0.89473684, 0.92982456, 0.91071429])

In [41]:
# Com Dropout
resultados.mean()

0.9244047619047621

In [42]:
# Com Dropout
resultados.std()

0.022351851272460296

## Tuning dos parametros

In [44]:
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

In [45]:
pd.__version__, tf.__version__, sklearn.__version__, scikeras.__version__

('2.2.2', '2.16.1', '1.4.2', '0.13.0')

In [47]:
from scikeras.wrappers import KerasClassifier
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import GridSearchCV

In [55]:
def criar_rede_tuning(optimizer, loss, kernel_initializer, activation, neurons):
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape = (30,)), 
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),# Aqui é a aplicação de um Dropout - não obrigatório para avaliar a rede_neural
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
    otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)
    rede_neural.compile(optimizer = optimizer, loss = loss, metrics = ['binary_accuracy'])
    return rede_neural

In [56]:
rede_neural = KerasClassifier(model = criar_rede_tuning)

In [57]:
parametros = {
    'batch_size': [10,30],
    'epochs': [50,100],
    'model__optimizer': ['adam','sgd'],
    'model__loss':['binary_crossentropy','hinge'],
    'model__kernel_initializer':['random_uniform','normal'],
    'model__activation': ['relu','tanh'],
    'model__neurons': [16,8]
}
parametros

{'batch_size': [10, 30],
 'epochs': [50, 100],
 'model__optimizer': ['adam', 'sgd'],
 'model__loss': ['binary_crossentropy', 'hinge'],
 'model__kernel_initializer': ['random_uniform', 'normal'],
 'model__activation': ['relu', 'tanh'],
 'model__neurons': [16, 8]}

In [58]:
parametros = {
    'batch_size': [10,30],
    'epochs': [50],
    'model__optimizer': ['adam'],
    'model__loss':['binary_crossentropy'],
    'model__kernel_initializer':['random_uniform','normal'],
    'model__activation': ['relu'],
    'model__neurons': [16]
}
# esta versão de parametros é menor para levar menos tempo localmente nos testes, em aplicacao normal, pode-se usar mais parametros
parametros

{'batch_size': [10, 30],
 'epochs': [50],
 'model__optimizer': ['adam'],
 'model__loss': ['binary_crossentropy'],
 'model__kernel_initializer': ['random_uniform', 'normal'],
 'model__activation': ['relu'],
 'model__neurons': [16]}

In [59]:
grid_search = GridSearchCV(estimator = rede_neural, param_grid = parametros, scoring = 'accuracy', cv = 5)

In [60]:
grid_search = grid_search.fit(X,y)

Epoch 1/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.6431 - loss: 0.78457
Epoch 2/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7964 - loss: 0.4852
Epoch 3/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8260 - loss: 0.4379
Epoch 4/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8614 - loss: 0.4460
Epoch 5/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9003 - loss: 0.2904
Epoch 6/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8801 - loss: 0.3047
Epoch 7/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8835 - loss: 0.3377
Epoch 8/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - binary_accuracy: 0.9096 - loss: 0.3025
Epoch 9/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9004 - loss: 0.2870
Epoch 10/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9113 - loss: 0.2609
Epoch 11/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9162 - loss: 0

In [61]:
print(grid_search)

GridSearchCV(cv=5,
             estimator=KerasClassifier(model=<function criar_rede_tuning at 0x775e97f4be20>),
             param_grid={'batch_size': [10, 30], 'epochs': [50],
                         'model__activation': ['relu'],
                         'model__kernel_initializer': ['random_uniform',
                                                       'normal'],
                         'model__loss': ['binary_crossentropy'],
                         'model__neurons': [16], 'model__optimizer': ['adam']},
             scoring='accuracy')


In [63]:
melhores_parametros = grid_search.best_params_

In [64]:
print(melhores_parametros)

{'batch_size': 10, 'epochs': 50, 'model__activation': 'relu', 'model__kernel_initializer': 'normal', 'model__loss': 'binary_crossentropy', 'model__neurons': 16, 'model__optimizer': 'adam'}


In [66]:
melhor_precisao = grid_search.best_score_
print(melhor_precisao)

0.9279459711224964


## Previsão de Valor - um unico registro

In [83]:
# É necessário converter os dados categóricos nominais em ordinais

In [84]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Converte os rótulos para numérico (0 e 1) caso sejam categóricos
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Converte X para float32 se ainda não estiver
X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.float32)

# Verificação opcional
print("X shape:", X.shape, "X dtype:", X.dtype)
print("y shape:", y.shape, "y dtype:", y.dtype)

X shape: (569, 30) X dtype: float32
y shape: (569,) y dtype: float32


/home/lucas/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [67]:
# Aqui o algoritmo já deve ter os melhores parametros definidos, e tambem ter feito o Tuning

In [85]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout

In [86]:
classificador = Sequential()
classificador.add(InputLayer(shape=(30,)))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=1, activation='sigmoid'))

In [87]:
classificador.compile(optimizer='adam',loss='binary_crossentropy',metrics=['binary_accuracy'])

In [88]:
classificador.fit(X,y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5809 - loss: 0.7958
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - binary_accuracy: 0.8309 - loss: 0.4979
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8766 - loss: 0.3720  
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8565 - loss: 0.3441
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8817 - loss: 0.3026
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8903 - loss: 0.3276
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9105 - loss: 0.2492
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8720 - loss: 0.3104
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9136 - loss: 0.2552  
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - binary_accuracy: 0.8992 - loss: 0.2546
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 

In [89]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [97]:
novo = np.array([[15.8,8.34,118,900,0.1,0.26,0.008,0.134,0.178,0.2,0.05,1098,0.87,4500,145.2,0.005,0.04,0.05,0.015,0.03,0.007,23.15,16.64,178.5,2018,0.14,0.185,0.84,158,0.363]])

In [98]:
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-03, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [99]:
novo.size, novo.shape

(30, (1, 30))

In [100]:
previsao = classificador.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


In [101]:
previsao

array([[1.]], dtype=float32)

In [103]:
previsao = previsao > 0.5
print(previsao)

[[ True]]


In [104]:
if previsao:
    print('Maligno')
else:
    print('Benigno')

Maligno


## Salvando o arquivo classificador

In [105]:
classificador.save('classificador_breast.keras')

## Carregando o arquivo do classificador

In [106]:
classificador_novo = tf.keras.models.load_model('classificador_breast.keras')

In [107]:
classificador_novo.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [108]:
classificador_novo.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[1.]], dtype=float32)