# Classificação binária - Brest Cancer Simples

Base de dados: https://archive.ics.uci.edu/dataset/17/breast+cancer+winsconsin+diagnostic

## Importando base de dados

In [2]:
import pandas as pd

In [3]:
# previsores 
X = pd.read_csv('2_cancer_entradas.csv')
X

radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
0      17.99     10.38      122.80  1001.0      0.11840       0.27760   
1      20.57     17.77      132.90  1326.0      0.08474       0.07864   
2      19.69     21.25      130.00  1203.0      0.10960       0.15990   
3      11.42     20.38       77.58   386.1      0.14250       0.28390   
4      20.29     14.34      135.10  1297.0      0.10030       0.13280   
..       ...       ...         ...     ...          ...           ...   
564    21.56     22.39      142.00  1479.0      0.11100       0.11590   
565    20.13     28.25      131.20  1261.0      0.09780       0.10340   
566    16.60     28.08      108.30   858.1      0.08455       0.10230   
567    20.60     29.33      140.10  1265.0      0.11780       0.27700   
568     7.76     24.54       47.92   181.0      0.05263       0.04362   

     concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
0       0.30010          0.14710     0.2419             0.07871  ...   25.380   
1       0.08690          0.07017     0.1812             0.05667  ...   24.990   
2       0.19740          0.12790     0.2069             0.05999  ...   23.570   
3       0.24140          0.10520     0.2597             0.09744  ...   14.910   
4       0.19800          0.10430     0.1809             0.05883  ...   22.540   
..          ...              ...        ...                 ...  ...      ...   
564     0.24390          0.13890     0.1726             0.05623  ...   25.450   
565     0.14400          0.09791     0.1752             0.05533  ...   23.690   
566     0.09251          0.05302     0.1590             0.05648  ...   18.980   
567     0.35140          0.15200     0.2397             0.07016  ...   25.740   
568     0.00000          0.00000     0.1587             0.05884  ...    9.456   

     texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
0       17.33      184.60  2019.0      0.16220       0.66560      0.7119   
1       23.41      158.80  1956.0      0.12380       0.18660      0.2416   
2       25.53      152.50  1709.0      0.14440       0.42450      0.4504   
3       26.50       98.87   567.7      0.20980       0.86630      0.6869   
4       16.67      152.20  1575.0      0.13740       0.20500      0.4000   
..        ...         ...     ...          ...           ...         ...   
564     26.40      166.10  2027.0      0.14100       0.21130      0.4107   
565     38.25      155.00  1731.0      0.11660       0.19220      0.3215   
566     34.12      126.70  1124.0      0.11390       0.30940      0.3403   
567     39.42      184.60  1821.0      0.16500       0.86810      0.9387   
568     30.37       59.16   268.6      0.08996       0.06444      0.0000   

     concave_points3  symmetry3  fractal_dimension3  
0             0.2654     0.4601             0.11890  
1             0.1860     0.2750             0.08902  
2             0.2430     0.3613             0.08758  
3             0.2575     0.6638             0.17300  
4             0.1625     0.2364             0.07678  
..               ...        ...                 ...  
564           0.2216     0.2060             0.07115  
565           0.1628     0.2572             0.06637  
566           0.1418     0.2218             0.07820  
567           0.2650     0.4087             0.12400  
568           0.0000     0.2871             0.07039  

[569 rows x 30 columns]

In [4]:
# saidas 
y = pd.read_csv('2_cancer_saidas.csv')
y

Diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

## Divisão base de treino e teste

In [5]:
import sklearn 
from sklearn.model_selection import train_test_split
sklearn.__version__

'1.4.2'

In [6]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X,y,test_size=0.25)

In [7]:
X_treinamento.shape , y_treinamento.shape

((426, 30), (426, 1))

In [8]:
X_teste.shape , y_teste.shape

((143, 30), (143, 1))

## Estrutura da Rede Neural

In [9]:
# Importacao desta lib para desativar erro no TensorFlow
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [10]:
# !pip uninstall -y tensorflow
!pip install -q tensorflow==2.16.1
import tensorflow as tf
from tensorflow.keras.models import Sequential
tf.__version__

'2.16.1'

In [11]:

# shape - numero de colunas do dataframe
# units - para calcular units, depende da quantidade de colunas (30) e de saidas (1) Pois é uma classificação binária
#
#    (30 + 1) / 2 = 15.5 => 16
#

rede_neural = Sequential([
     tf.keras.layers.InputLayer(shape = (30,)),
     tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
     tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
     tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

In [12]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

## Tratando a base de dados

É necessário converter os dados categóricos nominais em ordinais

In [13]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Converte os rótulos para numérico (0 e 1)
label_encoder = LabelEncoder()
y_treinamento = label_encoder.fit_transform(y_treinamento)
y_teste = label_encoder.fit_transform(y_teste)

# Converte X_treinamento para float32 se ainda não estiver
X_treinamento = np.array(X_treinamento, dtype=np.float32)
y_treinamento = np.array(y_treinamento, dtype=np.float32)
y_teste = np.array(y_teste, dtype=np.float32)

/home/lucas/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/lucas/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Configuração e execução da rede neural

In [14]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [15]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy'])

In [16]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 952us/step - binary_accuracy: 0.5576 - loss: 0.6800
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8662 - loss: 0.5210
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - binary_accuracy: 0.9206 - loss: 0.4032
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9058 - loss: 0.3246
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - binary_accuracy: 0.8531 - loss: 0.3379
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - binary_accuracy: 0.8716 - loss: 0.3155
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8988 - loss: 0.2927
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8973 - loss: 0.2581
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9125 - loss: 0.2522
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9024 - loss: 0.2936
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - binary_accuracy

In [17]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[ 1.44273974e-02,  2.89201029e-02,  5.52525856e-02,
          1.62495114e-02, -4.33660746e-02,  2.07671709e-02,
         -1.42325372e-01, -1.90053135e-01, -1.54604698e-02,
          1.83735684e-01, -1.13189511e-01, -7.43159503e-02,
          1.23550035e-01, -3.69168893e-02,  2.47527868e-01,
          8.23544711e-02],
        [ 1.56993531e-02,  3.63213085e-02, -1.04541808e-01,
         -3.62313613e-02, -3.32005396e-02,  3.67113464e-02,
         -5.90861402e-02, -9.57653299e-02,  5.37208356e-02,
          3.73818837e-02, -1.72302440e-01, -9.02030468e-02,
         -3.19544710e-02, -4.38475013e-02,  1.19204484e-01,
          1.77141521e-02],
        [-7.41265714e-04,  8.97526741e-03,  5.23012057e-02,
          2.82566659e-02, -1.31169446e-02,  4.97830808e-02,
          3.43771949e-02, -1.08028769e-01, -4.43641990e-02,
         -1.10002972e-01, -1.31271169e-01, -2.34554205e-02,
          2.00291142e-01, -3.46715078e-02, -1.49170145e-01,
         -7.48658227e-03],
        [-2.7001872

In [18]:
len(pesos0)

2

In [19]:
len(pesos0[1])

16

In [20]:
len(pesos0[0])

30

In [21]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[ 2.77868621e-02, -1.63936839e-02, -9.81631130e-03,
         -4.79373448e-02, -3.11376695e-02,  2.34288462e-02,
          3.61292996e-02,  4.24534939e-02, -2.40901113e-02,
         -1.94590446e-02, -2.69023329e-03, -4.99048829e-02,
          3.02897803e-02,  2.47155167e-02,  2.65322216e-02,
         -2.99944878e-02],
        [-1.25572905e-02, -4.19615731e-02,  4.06771936e-02,
         -2.34613549e-02, -4.68062162e-02, -3.46955657e-02,
         -2.56378409e-02,  4.36127447e-02,  7.19151646e-03,
          7.83971697e-03, -2.97908187e-02, -4.64372411e-02,
         -3.12462933e-02,  3.36826481e-02,  2.99917124e-02,
          1.77401043e-02],
        [-4.24949415e-02, -4.56724986e-02, -3.66477259e-02,
         -2.00723689e-02,  1.31010450e-02, -2.04166230e-02,
          2.21735667e-02, -6.68450631e-03, -2.31704377e-02,
          2.59786416e-02, -8.33727196e-02, -3.66557948e-02,
          1.77945625e-02, -1.25596421e-02,  1.78601518e-02,
         -3.68094444e-02],
        [ 4.0507230

In [22]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[ 0.30897984],
        [ 0.47936556],
        [-0.05808127],
        [ 0.579806  ],
        [-0.27464718],
        [ 0.4961585 ],
        [-0.28128788],
        [ 0.48573342],
        [ 0.3253216 ],
        [-0.22885276],
        [-0.06121534],
        [ 0.23051089],
        [-0.00222094],
        [ 0.2888078 ],
        [ 0.66373223],
        [ 0.45772028]], dtype=float32),
 array([-0.385601], dtype=float32)]

## Previsões

In [23]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5 # Convertendo o valor float com uma classe True/False

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step 


In [24]:
previsoes

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [

In [25]:
y_teste

array([0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 1., 1., 0.], dtype=float32)

## Comparação da base de previsão com a base de teste

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [27]:
accuracy_score(y_teste, previsoes)

0.9090909090909091

In [28]:
confusion_matrix(y_teste, previsoes)

array([[78,  8],
       [ 5, 52]])

In [29]:
rede_neural.evaluate(X_teste,y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9159 - loss: 0.2439  


[0.22766467928886414, 0.9090909361839294]

## Validação Cruzada

In [30]:
!pip install scikeras

In [31]:
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

In [32]:
pd.__version__ , tf.__version__, sklearn.__version__, scikeras.__version__

('2.2.2', '2.16.1', '1.4.2', '0.13.0')

In [33]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import cross_val_score
from tensorflow.keras.models import Sequential
from tensorflow.keras import backend as k

In [34]:
def criar_rede():
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape = (30,)), 
        tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
        tf.keras.layers.Dropout(rate = 0.2),# Aqui é a aplicação de um Dropout - não obrigatório para avaliar a rede_neural
        tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
    otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)
    rede_neural.compile(optimizer = otimizador, loss='binary_crossentropy', metrics = ['binary_accuracy'])
    return rede_neural

In [35]:
rede_neural = KerasClassifier(model = criar_rede, epochs=100, batch_size=10)

In [36]:
resultados = cross_val_score(estimator = rede_neural, X = X , y = y, cv = 10, scoring = 'accuracy')

Epoch 1/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5510 - loss: 1.0154
Epoch 2/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.5722 - loss: 0.6488
Epoch 3/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7880 - loss: 0.5058
Epoch 4/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8295 - loss: 0.4161
Epoch 5/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8060 - loss: 0.4136
Epoch 6/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8651 - loss: 0.3981
Epoch 7/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8720 - loss: 0.3329
Epoch 8/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8553 - loss: 0.3494
Epoch 9/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8915 - loss: 0.3381
Epoch 10/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8583 - loss: 0.3783
Epoch 11/100
52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8761 -

In [37]:
# Sem Dropout
resultados

array([0.9122807 , 0.92982456, 0.9122807 , 0.94736842, 0.94736842,
       0.89473684, 0.96491228, 0.89473684, 0.92982456, 0.91071429])

In [38]:
# Sem Dropout
resultados.mean()

0.9244047619047621

In [39]:
# Sem Dropout
resultados.std()

0.022351851272460296

In [40]:
# Com Dropout
resultados

array([0.9122807 , 0.92982456, 0.9122807 , 0.94736842, 0.94736842,
       0.89473684, 0.96491228, 0.89473684, 0.92982456, 0.91071429])

In [41]:
# Com Dropout
resultados.mean()

0.9244047619047621

In [42]:
# Com Dropout
resultados.std()

0.022351851272460296

## Tuning dos parametros

In [44]:
import pandas as pd
import tensorflow as tf
import sklearn
import scikeras

In [45]:
pd.__version__, tf.__version__, sklearn.__version__, scikeras.__version__

('2.2.2', '2.16.1', '1.4.2', '0.13.0')

In [47]:
from scikeras.wrappers import KerasClassifier
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import GridSearchCV

In [55]:
def criar_rede_tuning(optimizer, loss, kernel_initializer, activation, neurons):
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape = (30,)), 
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),# Aqui é a aplicação de um Dropout - não obrigatório para avaliar a rede_neural
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 1, activation = 'sigmoid')])
    otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)
    rede_neural.compile(optimizer = optimizer, loss = loss, metrics = ['binary_accuracy'])
    return rede_neural

In [56]:
rede_neural = KerasClassifier(model = criar_rede_tuning)

In [57]:
parametros = {
    'batch_size': [10,30],
    'epochs': [50,100],
    'model__optimizer': ['adam','sgd'],
    'model__loss':['binary_crossentropy','hinge'],
    'model__kernel_initializer':['random_uniform','normal'],
    'model__activation': ['relu','tanh'],
    'model__neurons': [16,8]
}
parametros

{'batch_size': [10, 30],
 'epochs': [50, 100],
 'model__optimizer': ['adam', 'sgd'],
 'model__loss': ['binary_crossentropy', 'hinge'],
 'model__kernel_initializer': ['random_uniform', 'normal'],
 'model__activation': ['relu', 'tanh'],
 'model__neurons': [16, 8]}

In [58]:
parametros = {
    'batch_size': [10,30],
    'epochs': [50],
    'model__optimizer': ['adam'],
    'model__loss':['binary_crossentropy'],
    'model__kernel_initializer':['random_uniform','normal'],
    'model__activation': ['relu'],
    'model__neurons': [16]
}
# esta versão de parametros é menor para levar menos tempo localmente nos testes, em aplicacao normal, pode-se usar mais parametros
parametros

{'batch_size': [10, 30],
 'epochs': [50],
 'model__optimizer': ['adam'],
 'model__loss': ['binary_crossentropy'],
 'model__kernel_initializer': ['random_uniform', 'normal'],
 'model__activation': ['relu'],
 'model__neurons': [16]}

In [59]:
grid_search = GridSearchCV(estimator = rede_neural, param_grid = parametros, scoring = 'accuracy', cv = 5)

In [60]:
grid_search = grid_search.fit(X,y)

Epoch 1/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.6431 - loss: 0.78457
Epoch 2/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - binary_accuracy: 0.7964 - loss: 0.4852
Epoch 3/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8260 - loss: 0.4379
Epoch 4/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8614 - loss: 0.4460
Epoch 5/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9003 - loss: 0.2904
Epoch 6/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8801 - loss: 0.3047
Epoch 7/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8835 - loss: 0.3377
Epoch 8/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - binary_accuracy: 0.9096 - loss: 0.3025
Epoch 9/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9004 - loss: 0.2870
Epoch 10/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.9113 - loss: 0.2609
Epoch 11/50
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9162 - loss: 0

In [61]:
print(grid_search)

GridSearchCV(cv=5,
             estimator=KerasClassifier(model=<function criar_rede_tuning at 0x775e97f4be20>),
             param_grid={'batch_size': [10, 30], 'epochs': [50],
                         'model__activation': ['relu'],
                         'model__kernel_initializer': ['random_uniform',
                                                       'normal'],
                         'model__loss': ['binary_crossentropy'],
                         'model__neurons': [16], 'model__optimizer': ['adam']},
             scoring='accuracy')


In [63]:
melhores_parametros = grid_search.best_params_

In [64]:
print(melhores_parametros)

{'batch_size': 10, 'epochs': 50, 'model__activation': 'relu', 'model__kernel_initializer': 'normal', 'model__loss': 'binary_crossentropy', 'model__neurons': 16, 'model__optimizer': 'adam'}


In [66]:
melhor_precisao = grid_search.best_score_
print(melhor_precisao)

0.9279459711224964


## Previsão de Valor - um unico registro

In [83]:
# É necessário converter os dados categóricos nominais em ordinais

In [84]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Converte os rótulos para numérico (0 e 1) caso sejam categóricos
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)

# Converte X para float32 se ainda não estiver
X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.float32)

# Verificação opcional
print("X shape:", X.shape, "X dtype:", X.dtype)
print("y shape:", y.shape, "y dtype:", y.dtype)

X shape: (569, 30) X dtype: float32
y shape: (569,) y dtype: float32


/home/lucas/anaconda3/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [67]:
# Aqui o algoritmo já deve ter os melhores parametros definidos, e tambem ter feito o Tuning

In [85]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, InputLayer, Dropout

In [86]:
classificador = Sequential()
classificador.add(InputLayer(shape=(30,)))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=16, activation='relu', kernel_initializer='random_uniform'))
classificador.add(Dropout(0.2))
classificador.add(Dense(units=1, activation='sigmoid'))

In [87]:
classificador.compile(optimizer='adam',loss='binary_crossentropy',metrics=['binary_accuracy'])

In [88]:
classificador.fit(X,y, batch_size=10, epochs=100)

Epoch 1/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5809 - loss: 0.7958
Epoch 2/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - binary_accuracy: 0.8309 - loss: 0.4979
Epoch 3/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8766 - loss: 0.3720  
Epoch 4/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.8565 - loss: 0.3441
Epoch 5/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8817 - loss: 0.3026
Epoch 6/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8903 - loss: 0.3276
Epoch 7/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9105 - loss: 0.2492
Epoch 8/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8720 - loss: 0.3104
Epoch 9/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.9136 - loss: 0.2552  
Epoch 10/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - binary_accuracy: 0.8992 - loss: 0.2546
Epoch 11/100
57/57 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 

In [89]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]], dtype=float32)

In [97]:
novo = np.array([[15.8,8.34,118,900,0.1,0.26,0.008,0.134,0.178,0.2,0.05,1098,0.87,4500,145.2,0.005,0.04,0.05,0.015,0.03,0.007,23.15,16.64,178.5,2018,0.14,0.185,0.84,158,0.363]])

In [98]:
novo

array([[1.580e+01, 8.340e+00, 1.180e+02, 9.000e+02, 1.000e-01, 2.600e-01,
        8.000e-03, 1.340e-01, 1.780e-01, 2.000e-01, 5.000e-02, 1.098e+03,
        8.700e-01, 4.500e+03, 1.452e+02, 5.000e-03, 4.000e-02, 5.000e-02,
        1.500e-02, 3.000e-02, 7.000e-03, 2.315e+01, 1.664e+01, 1.785e+02,
        2.018e+03, 1.400e-01, 1.850e-01, 8.400e-01, 1.580e+02, 3.630e-01]])

In [99]:
novo.size, novo.shape

(30, (1, 30))

In [100]:
previsao = classificador.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step


In [101]:
previsao

array([[1.]], dtype=float32)

In [103]:
previsao = previsao > 0.5
print(previsao)

[[ True]]


In [104]:
if previsao:
    print('Maligno')
else:
    print('Benigno')

Maligno


## Salvando o arquivo classificador

In [105]:
classificador.save('classificador_breast.keras')

## Carregando o arquivo do classificador

In [106]:
classificador_novo = tf.keras.models.load_model('classificador_breast.keras')

In [107]:
classificador_novo.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,357 (9.21 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,572 (6.14 KB)

In [108]:
classificador_novo.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[1.]], dtype=float32)