# Classificação Multiclass - Base Iris - DESAFIO

Base de dados: https://archive.ics.uci.edu/dataset/53/iris

## Importando base de dados

In [3]:
!pip install -q ucimlrepo

In [67]:
# Esta lib é indicada pela plataforma UCI , e ja faz a divisão dos previsores X e alvo y
from ucimlrepo import fetch_ucirepo 

# fetch dataset 
iris = fetch_ucirepo(id=53) 

# data (as pandas dataframes) 
X = iris.data.features
y = iris.data.targets

In [68]:
X = X.values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [69]:
y = y.iloc[:, 0].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## Instalando Bibliotecas

In [7]:
!pip install -q tensorflow==2.16.1

In [8]:
# Importacao desta lib para desativar erro no TensorFlow
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [9]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

2024-11-21 17:39:23.627846: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-21 17:39:23.631452: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-21 17:39:23.682510: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-21 17:39:24.763705: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [10]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '1.26.4', '2.16.1', '1.4.2')

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

## Convertendo os dados categoricos nominais em ordinais (apenas no alvo y)

In [70]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [71]:
# Precisa-se fazer a conversão abaixo para que a estrutura da rede neural consiga entender as saidas de cada classificacao
y = np_utils.to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [14]:
y.shape

(150, 3)

## Divisão de base de treino e teste

In [15]:
X_treinamento , X_teste, y_treinamento , y_teste = train_test_split(X,y,test_size=0.25)

In [16]:
X_treinamento.shape , X_teste.shape, y_treinamento.shape , y_teste.shape

((112, 4), (38, 4), (112, 3), (38, 3))

## Estrutura Rede Neural

In [17]:
# Para calcular a quantidade de neurônios na cadama oculta

# numero de entrada (previsores) + numeros de saidas (alvo) / 2

(4+3)/2

3.5

In [18]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dropout(rate = 0.2),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dropout(rate = 0.2),
    tf.keras.layers.Dense(units=3,activation='softmax'),
])

In [19]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
rede_neural.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [ ]:
rede_neural.fit(X_treinamento,y_treinamento, batch_size=10, epochs=2000)

Epoch 1/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - categorical_accuracy: 0.3581 - loss: 2.0431 
Epoch 2/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3072 - loss: 1.91254
Epoch 3/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3197 - loss: 1.6678
Epoch 4/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3877 - loss: 1.3963
Epoch 5/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3001 - loss: 1.5529
Epoch 6/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3081 - loss: 1.2713 
Epoch 7/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2955 - loss: 1.3497
Epoch 8/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3379 - loss: 1.1758
Epoch 9/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3613 - loss: 1.1228
Epoch 10/2000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2870 - loss: 1.1281
Epoch 11/2000
12

## Avaliando desempenho Rede Neural

In [32]:
rede_neural.evaluate(X_teste,y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - categorical_accuracy: 0.9441 - loss: 0.1261 


[0.12277694791555405, 0.9473684430122375]

In [33]:
previsoes = rede_neural.predict(X_teste)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
[[1.59029623e-09 7.68796876e-02 9.23120379e-01]
 [9.64504004e-01 3.54960449e-02 0.00000000e+00]
 [1.53996352e-05 4.14000392e-01 5.85984170e-01]
 [2.88782344e-12 1.49640506e-02 9.85035956e-01]
 [9.68153954e-01 3.18460912e-02 0.00000000e+00]
 [3.87103260e-01 6.12896800e-01 1.56073213e-18]
 [9.61621523e-01 3.83784585e-02 0.00000000e+00]
 [2.01410614e-03 9.97985780e-01 7.54126983e-09]
 [1.58467365e-03 9.98413801e-01 1.57527802e-06]
 [3.24456400e-04 9.87944543e-01 1.17309503e-02]
 [1.68171724e-07 2.32849956e-01 7.67149925e-01]
 [5.83655568e-10 5.96394800e-02 9.40360487e-01]
 [1.38840079e-03 9.92271423e-01 6.34008599e-03]
 [9.71863389e-01 2.81366333e-02 0.00000000e+00]
 [7.97918346e-03 9.92020726e-01 2.73368950e-09]
 [9.49673533e-01 5.03264368e-02 0.00000000e+00]
 [9.81261790e-01 1.87382400e-02 0.00000000e+00]
 [1.01787573e-05 4.08681154e-01 5.91308653e-01]
 [5.85451582e-03 9.94145513e-01 1.63262541e-08]
 [9.50326741e-01 4.96732295e-02 0.00000000e+00]
 [

In [34]:
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]]


In [35]:
y_teste

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [36]:
y_Teste2 = [np.argmax(t) for t in y_teste]

In [37]:
print(y_Teste2)

[2, 0, 2, 2, 0, 1, 0, 1, 1, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 0]


In [38]:
previsoes2 = [np.argmax(t) for t in previsoes] 

In [39]:
print(previsoes2)

[2, 0, 2, 2, 0, 1, 0, 1, 1, 1, 2, 2, 1, 0, 1, 0, 0, 2, 1, 0, 2, 0, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 0]


In [40]:
from sklearn.metrics import accuracy_score
accuracy_score(y_Teste2, previsoes2)

0.9473684210526315

In [41]:
confusion_matrix(y_Teste2, previsoes2)

array([[13,  0,  0],
       [ 0, 15,  2],
       [ 0,  0,  8]])

## Validação Cruzada

In [97]:
!pip install -q scikeras

In [98]:
import scikeras

In [99]:
scikeras.__version__

'0.13.0'

In [44]:
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [45]:
def criar_rede():
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape=(4,)),
        tf.keras.layers.Dense(units=5,activation='relu'),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units=5,activation='relu'),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units=3,activation='softmax'),
    ])
    rede_neural.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])
    return rede_neural

In [46]:
rede_neural = KerasClassifier(model = criar_rede, epochs = 250, batch_size = 10)

In [47]:
resultados = cross_val_score(estimator = rede_neural, X = X, y=y, cv=10, scoring='accuracy')

Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - categorical_accuracy: 0.3644 - loss: 1.4232   
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4415 - loss: 1.2113
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3514 - loss: 1.3283
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4133 - loss: 1.1303 
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3395 - loss: 1.2853
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4197 - loss: 1.0763
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3363 - loss: 1.0594 
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4637 - loss: 0.9903
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3203 - loss: 1.0988 
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3886 - loss: 1.0656
Epoch 11/250
14/14 ━━━━

In [48]:
resultados

array([1.        , 1.        , 1.        , 0.33333333, 0.8       ,
       0.        , 0.        , 0.4       , 0.6       , 0.        ])

In [49]:
resultados.mean()

0.5133333333333333

In [50]:
resultados.std()

0.4044749683231337

## Desafio - Tuning de parametros Rede Neural

### Estrutura

In [52]:
from scikeras.wrappers import KerasClassifier
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import GridSearchCV

In [74]:
def criar_rede_tuning(optimizer, loss, kernel_initializer, activation, neurons):
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape = (4,)), 
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),# Aqui é a aplicação de um Dropout - não obrigatório para avaliar a rede_neural
        tf.keras.layers.Dense(units = neurons, activation = activation, kernel_initializer = kernel_initializer),
        tf.keras.layers.Dropout(rate = 0.2),
        tf.keras.layers.Dense(units = 3, activation = 'softmax')])
    otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)
    rede_neural.compile(optimizer = optimizer, loss = loss, metrics = ['accuracy'])
    return rede_neural

In [75]:
rede_neural = KerasClassifier(model = criar_rede_tuning)

In [76]:
parametros = {
    'batch_size': [10,30],
    'epochs': [250,300],
    'model__optimizer': ['adam'],
    'model__loss':['categorical_crossentropy'],
    'model__kernel_initializer':['random_uniform','normal'],
    'model__activation': ['relu'],
    'model__neurons': [4,5]
}
parametros

{'batch_size': [10, 30],
 'epochs': [250, 300],
 'model__optimizer': ['adam'],
 'model__loss': ['categorical_crossentropy'],
 'model__kernel_initializer': ['random_uniform', 'normal'],
 'model__activation': ['relu'],
 'model__neurons': [4, 5]}

In [77]:
grid_search = GridSearchCV(estimator = rede_neural, param_grid = parametros, cv = 5)

In [78]:
grid_search = grid_search.fit(X,y)

Epoch 1/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3969 - loss: 1.0954 
Epoch 2/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4375 - loss: 1.0877  
Epoch 3/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4409 - loss: 1.0845
Epoch 4/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4908 - loss: 1.0623
Epoch 5/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3653 - loss: 1.0737
Epoch 6/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4334 - loss: 1.0550
Epoch 7/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4431 - loss: 1.0374
Epoch 8/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4389 - loss: 1.0430
Epoch 9/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4288 - loss: 1.0284
Epoch 10/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4303 - loss: 1.0435
Epoch 11/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3450 - loss: 1.0679
Epoch 12/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accura

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.2711 - loss: 1.1009
Epoch 2/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4817 - loss: 1.0963
Epoch 3/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5301 - loss: 1.0947
Epoch 4/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5470 - loss: 1.0971
Epoch 5/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4691 - loss: 1.0961
Epoch 6/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6079 - loss: 1.0839
Epoch 7/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5381 - loss: 1.0805
Epoch 8/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5346 - loss: 1.0693
Epoch 9/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5652 - loss: 1.0654
Epoch 10/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5725 - loss: 1.0622
Epoch 11/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7142 - loss: 1.0349
Epoch 12/250
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6530 - lo

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7044 - loss: 0.7067
Epoch 171/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7033 - loss: 0.6850
Epoch 172/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7833 - loss: 0.6758
Epoch 173/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7456 - loss: 0.6621 
Epoch 174/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7817 - loss: 0.6448
Epoch 175/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7422 - loss: 0.6832
Epoch 176/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7133 - loss: 0.7194
Epoch 177/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6556 - loss: 0.7268
Epoch 178/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7567 - loss: 0.6792 
Epoch 179/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7211 - loss: 0.6947
Epoch 180/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7933 - loss: 0.6363
Epoch 181/250
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7600 - loss:

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [79]:
print(grid_search)

GridSearchCV(cv=5,
             estimator=KerasClassifier(model=<function criar_rede_tuning at 0x7975fb43cd60>),
             param_grid={'batch_size': [10, 30], 'epochs': [250, 300],
                         'model__activation': ['relu'],
                         'model__kernel_initializer': ['random_uniform',
                                                       'normal'],
                         'model__loss': ['categorical_crossentropy'],
                         'model__neurons': [4, 5],
                         'model__optimizer': ['adam']})


In [80]:
melhores_parametros = grid_search.best_params_

In [81]:
print(melhores_parametros)

{'batch_size': 10, 'epochs': 300, 'model__activation': 'relu', 'model__kernel_initializer': 'normal', 'model__loss': 'categorical_crossentropy', 'model__neurons': 5, 'model__optimizer': 'adam'}


In [82]:
melhor_precisao = grid_search.best_score_
print(melhor_precisao)

0.8866666666666667


## Desafio - Classificar somente uma planta

In [83]:
classificador = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=5,activation='relu'),
    tf.keras.layers.Dropout(rate = 0.2),
    tf.keras.layers.Dense(units=5,activation='relu'),
    tf.keras.layers.Dropout(rate = 0.2),
    tf.keras.layers.Dense(units=3,activation='softmax'),
])

In [84]:
classificador.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [85]:
classificador.fit(X,y, batch_size=10, epochs=300)

Epoch 1/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4595 - loss: 0.99114
Epoch 2/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4712 - loss: 1.0141
Epoch 3/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4716 - loss: 0.9927 
Epoch 4/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5128 - loss: 0.9852
Epoch 5/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4348 - loss: 0.9870
Epoch 6/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4614 - loss: 0.9741
Epoch 7/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4513 - loss: 0.9589 
Epoch 8/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4914 - loss: 0.9485 
Epoch 9/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6124 - loss: 0.8549
Epoch 10/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5995 - loss: 0.8301
Epoch 11/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5737 - loss: 0.8537
Epoch 12/300
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accur

In [87]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [94]:
novo = np.array([[4.8, 3.4, 1.6, 0.2]])
novo.size, novo.shape

(4, (1, 4))

In [95]:
previsao = classificador.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


In [96]:
previsao = previsao > 0.5
print(previsao)

[[ True False False]]


In [97]:
previsao_final = [np.argmax(t) for t in previsao] 
previsao_final

[0]

## Desafio - Salvar o classificador

In [98]:
classificador.save('classificador_base_iris.keras')

## Carregando o arquivo do classificador

In [99]:
classificador_novo = tf.keras.models.load_model('classificador_base_iris.keras')

In [100]:
classificador_novo.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 5)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 5)              │            30 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 5)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            18 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 221 (888.00 B)

 Trainable params: 73 (292.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 148 (596.00 B)

In [101]:
classificador_novo.predict(novo)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[8.86540949e-01, 1.13459110e-01, 1.09178985e-11]], dtype=float32)