# Classificação Multiclass - Base Iris

Base de dados: https://archive.ics.uci.edu/dataset/53/iris

## Importando base de dados

In [1]:
!pip install -q ucimlrepo

In [26]:
# Esta lib é indicada pela plataforma UCI , e ja faz a divisão dos previsores X e alvo y
from ucimlrepo import fetch_ucirepo 

# fetch dataset 
iris = fetch_ucirepo(id=53) 

# data (as pandas dataframes) 
X = iris.data.features
y = iris.data.targets

In [27]:
X = X.values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [28]:
X.shape

(150, 4)

In [29]:
y = y.iloc[:, 0].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [30]:
y.shape

(150,)

## Instalando Bibliotecas

In [31]:
!pip install -q tensorflow==2.16.1

In [32]:
# Importacao desta lib para desativar erro no TensorFlow
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [33]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

In [34]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '1.26.4', '2.16.1', '1.4.2')

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

## Convertendo os dados categoricos nominais em ordinais (apenas no alvo y)

In [36]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
# Precisa-se fazer a conversão abaixo para que a estrutura da rede neural consiga entender as saidas de cada classificacao
y = np_utils.to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [38]:
y.shape

(150, 3)

## Divisão de base de treino e teste

In [39]:
X_treinamento , X_teste, y_treinamento , y_teste = train_test_split(X,y,test_size=0.25)

In [40]:
X_treinamento.shape , X_teste.shape, y_treinamento.shape , y_teste.shape

((112, 4), (38, 4), (112, 3), (38, 3))

## Estrutura Rede Neural

In [41]:
# Para calcular a quantidade de neurônios na camada oculta

# numero de entrada (previsores) + numeros de saidas (alvo) / 2

(4+3)/2

3.5

In [42]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dense(units=3,activation='softmax'),
])

In [43]:
rede_neural.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
rede_neural.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [45]:
rede_neural.fit(X_treinamento,y_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.3192 - loss: 1.11310
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.5125 - loss: 1.0792
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.4505 - loss: 1.0424
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.5604 - loss: 0.9881
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4707 - loss: 0.9704
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4969 - loss: 0.9196
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4926 - loss: 0.9206
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.5891 - loss: 0.8837
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4997 - loss: 0.9199
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.4837 - loss: 0.8976
Epoch 11/1000
12/1

## Avaliando desempenho Rede Neural

In [47]:
rede_neural.evaluate(X_teste,y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 1.0000 - loss: 0.0491 


[0.05248738452792168, 1.0]

In [48]:
previsoes = rede_neural.predict(X_teste)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[7.7681663e-04 3.1417221e-02 9.6780592e-01]
 [1.4994922e-03 6.1358052e-01 3.8492003e-01]
 [9.9999231e-01 7.6654987e-06 6.2620214e-15]
 [9.9999815e-01 1.7512207e-06 3.7804050e-17]
 [9.9999982e-01 7.1747316e-08 9.9237902e-19]
 [9.9999923e-01 7.1037732e-07 5.1429984e-17]
 [7.7681663e-04 3.1417221e-02 9.6780592e-01]
 [9.9999958e-01 3.7300774e-07 1.9574615e-17]
 [9.9999994e-01 4.6339350e-09 5.5012107e-21]
 [9.9999505e-01 4.8683669e-06 1.7756729e-15]
 [1.9779356e-04 9.9061561e-01 9.1865696e-03]
 [9.9999660e-01 3.3966510e-06 2.4664666e-15]
 [7.7681663e-04 3.1417221e-02 9.6780592e-01]
 [6.3940679e-04 9.3031192e-01 6.9048628e-02]
 [9.9999970e-01 2.1565563e-07 4.4973169e-18]
 [9.9998802e-01 1.1973099e-05 2.6685832e-15]
 [7.2169540e-05 9.9825233e-01 1.6755080e-03]
 [1.3607149e-06 9.9999648e-01 2.0983534e-06]
 [4.6873470e-06 9.9997848e-01 1.6815004e-05]
 [4.0343120e-06 9.9999183e-01 4.0855321e-06]
 [7.7681663e-04 3.1417221e-02 9.6780592e-01]
 [7.7681663e-04 3

In [49]:
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]]


In [23]:
y_teste

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [50]:
y_teste2 = [np.argmax(t) for t in y_teste]

In [51]:
print(y_teste2)

[2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 2, 2, 1, 1, 0]


In [52]:
previsoes2 = [np.argmax(t) for t in previsoes] 

In [53]:
print(previsoes2)

[2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 2, 2, 1, 1, 0]


In [54]:
from sklearn.metrics import accuracy_score
accuracy_score(y_teste2, previsoes2)

1.0

In [55]:
confusion_matrix(y_teste2, previsoes2)

array([[14,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 10]])

## Validação Cruzada

In [56]:
!pip install -q scikeras

In [57]:
import scikeras

In [58]:
scikeras.__version__

'0.13.0'

In [59]:
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [60]:
def criar_rede():
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape=(4,)),
        tf.keras.layers.Dense(units=4, activation='relu'),
        tf.keras.layers.Dense(units=4, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax'),
    ])
    rede_neural.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])
    return rede_neural

In [61]:
rede_neural = KerasClassifier(model = criar_rede, epochs = 250, batch_size = 10)

In [ ]:
resultados = cross_val_score(estimator = rede_neural, X = X, y=y, cv=10, scoring='accuracy')

Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.3802 - loss: 1.9950
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.4033 - loss: 1.6230
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3470 - loss: 1.5334
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3632 - loss: 1.3311 
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3681 - loss: 1.2212
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4093 - loss: 1.1510
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3396 - loss: 1.1683
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - categorical_accuracy: 0.3866 - loss: 1.1142
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.4111 - loss: 1.0737
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3816 - loss: 1.0862
Epoch 11/250
14/14 ━━━━━━━━━

In [66]:
resultados

array([1.        , 1.        , 1.        , 1.        , 0.8       ,
       0.93333333, 1.        , 0.        , 0.8       , 0.        ])

In [67]:
resultados.mean()

0.7533333333333333

In [68]:
resultados.std()

0.38418745424597095