# Classificação Multiclass - Base Iris

Base de dados: https://archive.ics.uci.edu/dataset/53/iris

## Importando base de dados

In [1]:
!pip install -q ucimlrepo

In [2]:
# Esta lib é indicada pela plataforma UCI , e ja faz a divisão dos previsores X e alvo y
from ucimlrepo import fetch_ucirepo 

# fetch dataset 
iris = fetch_ucirepo(id=53) 

# data (as pandas dataframes) 
X = iris.data.features
y = iris.data.targets

In [3]:
X = X.values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = y.iloc[:, 0].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## Instalando Bibliotecas

In [5]:
!pip install -q tensorflow==2.16.1

In [6]:
# Importacao desta lib para desativar erro no TensorFlow
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [7]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

2024-11-20 11:23:26.867493: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-20 11:23:27.079414: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-20 11:23:27.826799: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-20 11:23:29.766084: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [8]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '1.26.4', '2.16.1', '1.4.2')

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

## Convertendo os dados categoricos nominais em ordinais (apenas no alvo y)

In [10]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# Precisa-se fazer a conversão abaixo para que a estrutura da rede neural consiga entender as saidas de cada classificacao
y = np_utils.to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [12]:
y.shape

(150, 3)

## Divisão de base de treino e teste

In [13]:
X_treinamento , X_teste, y_treinamento , y_teste = train_test_split(X,y,test_size=0.25)

In [14]:
X_treinamento.shape , X_teste.shape, y_treinamento.shape , y_teste.shape

((112, 4), (38, 4), (112, 3), (38, 3))

## Estrutura Rede Neural

In [15]:
# Para calcular a quantidade de neurônios na cadama oculta

# numero de entrada (previsores) + numeros de saidas (alvo) / 2

(4+3)/2

3.5

In [16]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dense(units=3,activation='softmax'),
])

In [17]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
rede_neural.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [19]:
rede_neural.fit(X_treinamento,y_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.3051 - loss: 5.5425
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.3595 - loss: 4.5273
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3655 - loss: 4.0684
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3598 - loss: 3.9810
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2793 - loss: 4.0549
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3415 - loss: 3.3198
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2658 - loss: 3.3074 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3720 - loss: 2.5608
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2980 - loss: 2.5943
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2908 - loss: 2.6501
Epoch 11/1000
12/1

## Avaliando desempenho Rede Neural

In [22]:
rede_neural.evaluate(X_teste,y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.9720 - loss: 0.1062


[0.1057419627904892, 0.9736841917037964]

In [23]:
previsoes = rede_neural.predict(X_teste)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
[[1.17811164e-10 4.39201221e-02 9.56079841e-01]
 [6.77622836e-07 9.95632827e-01 4.36642114e-03]
 [7.64778345e-12 7.68923340e-03 9.92310703e-01]
 [8.25329565e-08 9.79714096e-01 2.02857684e-02]
 [7.14682642e-08 9.80042696e-01 1.99572071e-02]
 [9.99826193e-01 1.59429124e-04 1.44199557e-05]
 [1.48827965e-07 9.83375549e-01 1.66242644e-02]
 [4.06100457e-12 1.02365548e-02 9.89763319e-01]
 [9.99832392e-01 1.53638757e-04 1.39996255e-05]
 [8.02580326e-20 1.07640375e-07 9.99999821e-01]
 [1.85645512e-13 1.04243646e-03 9.98957396e-01]
 [9.99410272e-01 5.50855300e-04 3.88609769e-05]
 [9.10620646e-13 2.49610585e-03 9.97503936e-01]
 [1.78929781e-14 3.11355863e-04 9.99688625e-01]
 [4.60146566e-06 9.94860828e-01 5.13449404e-03]
 [1.47163846e-07 9.96162832e-01 3.83699872e-03]
 [9.99889791e-01 1.00271624e-04 9.95240862e-06]
 [1.44708075e-16 1.90336377e-05 9.99980867e-01]
 [1.66218670e-03 9.88157153e-01 1.01805888e-02]
 [4.78550477e-10 1.49685040e-01 8.50314915e-01]
 [

In [24]:
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False  True False]]


In [25]:
y_teste

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [26]:
y_Teste2 = [np.argmax(t) for t in y_teste]

In [27]:
print(y_Teste2)

[1, 1, 2, 1, 1, 0, 1, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1]


In [28]:
previsoes2 = [np.argmax(t) for t in previsoes] 

In [29]:
print(previsoes2)

[2, 1, 2, 1, 1, 0, 1, 2, 0, 2, 2, 0, 2, 2, 1, 1, 0, 2, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1]


In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_Teste2, previsoes2)

0.9736842105263158

In [31]:
confusion_matrix(y_Teste2, previsoes2)

array([[ 9,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 14]])

## Validação Cruzada

In [32]:
!pip install -q scikeras

In [33]:
import scikeras

In [34]:
scikeras.__version__

'0.13.0'

In [35]:
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [36]:
def criar_rede():
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape=(4,)),
        tf.keras.layers.Dense(units=4, activation='relu'),
        tf.keras.layers.Dense(units=4, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax'),
    ])
    rede_neural.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])
    return rede_neural

In [37]:
rede_neural = KerasClassifier(model = criar_rede, epochs = 250, batch_size = 10)

In [ ]:
resultados = cross_val_score(estimator = rede_neural, X = X, y=y, cv=10, scoring='accuracy')

Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - categorical_accuracy: 0.2683 - loss: 1.1216     
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3320 - loss: 1.1109
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4264 - loss: 1.1026
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3670 - loss: 1.0993
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3797 - loss: 1.0982
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3767 - loss: 1.0947
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.4179 - loss: 1.0947
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3857 - loss: 1.0916 
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3006 - loss: 1.0928  
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3678 - loss: 1.0944 
Epoch 11/250
14/14 ━

In [42]:
resultados

array([1.        , 1.        , 1.        , 1.        , 0.73333333,
       0.8       , 1.        , 0.93333333, 0.73333333, 0.93333333])

In [43]:
resultados.mean()

0.9133333333333333

In [44]:
resultados.std()

0.1077032961426901