# Classificação Multiclass - Base Iris

Base de dados: https://archive.ics.uci.edu/dataset/53/iris

## Importando base de dados

In [1]:
!pip install -q ucimlrepo

In [2]:
# Esta lib é indicada pela plataforma UCI , e ja faz a divisão dos previsores X e alvo y
from ucimlrepo import fetch_ucirepo 

# fetch dataset 
iris = fetch_ucirepo(id=53) 

# data (as pandas dataframes) 
X = iris.data.features
y = iris.data.targets

In [3]:
X = X.values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y = y.iloc[:, 0].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

## Instalando Bibliotecas

In [5]:
!pip install -q tensorflow==2.16.1

In [6]:
# Importacao desta lib para desativar erro no TensorFlow
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

In [7]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn

2024-11-21 17:18:16.727231: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-21 17:18:16.979983: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-11-21 17:18:17.870744: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-11-21 17:18:19.857197: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [8]:
pd.__version__, np.__version__, tf.__version__, sklearn.__version__

('2.2.2', '1.26.4', '2.16.1', '1.4.2')

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

## Convertendo os dados categoricos nominais em ordinais (apenas no alvo y)

In [10]:
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# Precisa-se fazer a conversão abaixo para que a estrutura da rede neural consiga entender as saidas de cada classificacao
y = np_utils.to_categorical(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [12]:
y.shape

(150, 3)

## Divisão de base de treino e teste

In [13]:
X_treinamento , X_teste, y_treinamento , y_teste = train_test_split(X,y,test_size=0.25)

In [14]:
X_treinamento.shape , X_teste.shape, y_treinamento.shape , y_teste.shape

((112, 4), (38, 4), (112, 3), (38, 3))

## Estrutura Rede Neural

In [15]:
# Para calcular a quantidade de neurônios na cadama oculta

# numero de entrada (previsores) + numeros de saidas (alvo) / 2

(4+3)/2

3.5

In [16]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dense(units=4,activation='relu'),
    tf.keras.layers.Dense(units=3,activation='softmax'),
])

In [17]:
rede_neural.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
rede_neural.compile(optimizer = 'adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [19]:
rede_neural.fit(X_treinamento,y_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.3359 - loss: 3.1050
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3826 - loss: 2.4021
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2049 - loss: 2.2467
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.1613 - loss: 1.8537
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2759 - loss: 1.6173
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3556 - loss: 1.4732
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.3177 - loss: 1.3119
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.5374 - loss: 1.1310
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6478 - loss: 1.1320 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6157 - loss: 1.0516 
Epoch 11/1000
12/

## Avaliando desempenho Rede Neural

In [20]:
rede_neural.evaluate(X_teste,y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 1.0000 - loss: 0.0243  


[0.027872586622834206, 1.0]

In [21]:
previsoes = rede_neural.predict(X_teste)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[9.99992788e-01 7.19754371e-06 3.24990295e-12]
 [3.26351437e-06 9.98956919e-01 1.03979395e-03]
 [9.99993265e-01 6.65419338e-06 1.86328947e-12]
 [5.46675619e-06 9.99786377e-01 2.08173136e-04]
 [6.65529171e-07 9.95370686e-01 4.62860754e-03]
 [8.33536920e-11 1.69283524e-03 9.98307228e-01]
 [1.97601848e-11 2.33562267e-03 9.97664392e-01]
 [9.69400048e-07 9.97600257e-01 2.39873119e-03]
 [4.17481579e-06 9.94373858e-01 5.62201487e-03]
 [9.99963462e-01 3.64836160e-05 1.22373067e-11]
 [4.19140243e-12 2.31860817e-04 9.99768257e-01]
 [7.83841074e-07 9.98692989e-01 1.30608492e-03]
 [4.68658845e-06 9.96829987e-01 3.16526764e-03]
 [2.92511668e-05 9.99065161e-01 9.05558933e-04]
 [5.81617365e-10 2.49939542e-02 9.75006044e-01]
 [9.99905884e-01 9.40500540e-05 2.46484805e-10]
 [9.99917448e-01 8.24432063e-05 1.09617364e-10]
 [6.68464173e-10 1.48048505e-01 8.51951540e-01]
 [3.27943432e-08 2.40029365e-01 7.59970605e-01]
 [9.99962747e-01 3.72155118e-05 5.48369648e-11]
 [

In [22]:
previsoes = previsoes > 0.5
print(previsoes)

[[ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]]


In [23]:
y_teste

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [24]:
y_Teste2 = [np.argmax(t) for t in y_teste]

In [25]:
print(y_Teste2)

[0, 1, 0, 1, 1, 2, 2, 1, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 2, 0, 1, 2, 1, 0, 0, 2, 0, 1]


In [26]:
previsoes2 = [np.argmax(t) for t in previsoes] 

In [27]:
print(previsoes2)

[0, 1, 0, 1, 1, 2, 2, 1, 1, 0, 2, 1, 1, 1, 2, 0, 0, 2, 2, 0, 1, 0, 1, 1, 2, 2, 2, 0, 2, 0, 1, 2, 1, 0, 0, 2, 0, 1]


In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_Teste2, previsoes2)

1.0

In [ ]:
confusion_matrix(y_Teste2, previsoes2)

array([[12,  0,  0],
       [ 0, 14,  0],
       [ 0,  0, 12]])

## Validação Cruzada

In [30]:
!pip install -q scikeras

In [31]:
import scikeras

In [32]:
scikeras.__version__

'0.13.0'

In [33]:
from scikeras.wrappers import KerasClassifier
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import utils as np_utils
from tensorflow.keras import backend as k
from tensorflow.keras.models import Sequential
from sklearn.model_selection import cross_val_score

In [34]:
def criar_rede():
    k.clear_session()
    rede_neural = Sequential([
        tf.keras.layers.InputLayer(shape=(4,)),
        tf.keras.layers.Dense(units=4, activation='relu'),
        tf.keras.layers.Dense(units=4, activation='relu'),
        tf.keras.layers.Dense(units=3, activation='softmax'),
    ])
    rede_neural.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])
    return rede_neural

In [35]:
rede_neural = KerasClassifier(model = criar_rede, epochs = 250, batch_size = 10)

In [ ]:
resultados = cross_val_score(estimator = rede_neural, X = X, y=y, cv=10, scoring='accuracy')

Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.2523 - loss: 5.8833 
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2634 - loss: 4.8359
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2806 - loss: 4.3409
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2850 - loss: 3.7152
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2325 - loss: 3.6646   
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.2932 - loss: 2.9393
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2240 - loss: 2.8103
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.2565 - loss: 2.4664
Epoch 9/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.2402 - loss: 2.1849 
Epoch 10/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.3220 - loss: 1.7658
Epoch 11/250
14/14 ━━━━━

In [40]:
resultados

array([1.        , 1.        , 1.        , 1.        , 0.86666667,
       0.8       , 1.        , 1.        , 0.93333333, 0.        ])

In [41]:
resultados.mean()

0.86

In [42]:
resultados.std()

0.29431653406192154