## Recomendação

Documentação: https://github.com/echen/restricted-boltzmann-machines

## Importação de bibliotecas

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [4]:
## Esta importacao é do arquivo na raiz rbm.py
import rbm

## Criação da RBM

In [5]:
rbm = rbm.RBM(num_visible = 6, num_hidden=2)

## Criação da Base de Dados

In [6]:
base =  np.array([
            [1,1,1,0,0,0],
            [1,0,1,0,0,0],
            [1,1,1,0,0,0],
            [0,0,1,1,1,1],
            [0,0,1,1,0,1],
            [0,0,1,1,0,1],
        ])

In [7]:
base.shape

(6, 6)

In [8]:
filmes = ["A bruxa","Invocação do mal","O chamado","Se beber não case","Gente grande","American Pie"]

## Treinamento

In [9]:
rbm.train(base,max_epochs=5000)

Epoch 0: error is 9.073361791782256
Epoch 1: error is 8.860032915696529
Epoch 2: error is 8.773083190078104
Epoch 3: error is 8.594361078946786
Epoch 4: error is 8.486897633151488
Epoch 5: error is 8.249318844766014
Epoch 6: error is 8.197890434351873
Epoch 7: error is 8.09625123538455
Epoch 8: error is 7.9649012269433594
Epoch 9: error is 7.863908031282927
Epoch 10: error is 7.8076538034781455
Epoch 11: error is 7.907973309768485
Epoch 12: error is 7.790235255273902
Epoch 13: error is 7.612377294393513
Epoch 14: error is 7.696372873261832
Epoch 15: error is 7.293229447216209
Epoch 16: error is 7.4845630121150135
Epoch 17: error is 7.43081397552777
Epoch 18: error is 7.265954304644854
Epoch 19: error is 7.235352854948491
Epoch 20: error is 7.206018905496949
Epoch 21: error is 7.417952347396638
Epoch 22: error is 7.507536103738107
Epoch 23: error is 7.282453776970441
Epoch 24: error is 7.025480183107067
Epoch 25: error is 7.011792154057779
Epoch 26: error is 7.001207805158474
Epoch 27: 

In [10]:
rbm.weights, rbm.weights.shape

(array([[ 2.47970582,  2.33524907,  0.37564142],
        [-1.04435714, -3.24861718,  7.96157447],
        [ 0.2121567 , -7.26945927,  3.31553373],
        [ 4.94911597,  3.90229408,  1.87746479],
        [ 0.98835062,  3.59272233, -8.24675203],
        [-1.30294194,  0.59802241, -4.55903567],
        [ 0.99337567,  3.58889866, -8.24930304]]),
 (7, 3))

## Recomendação de filmes

In [13]:
usuario1 = np.array([[1,1,0,1,0,0]])
usuario2 = np.array([[0,0,0,1,1,0]])

In [12]:
rbm.run_visible(usuario1)

array([[0., 1.]])

In [14]:
rbm.run_visible(usuario2)

array([[1., 0.]])

In [15]:
camada_escondida = np.array([[1,0]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[0., 0., 1., 1., 0., 1.]])

### Mostrar os filmes recomendados

In [16]:
for i in range(len(usuario1[0])):
    if usuario2[0, i] == 0 and recomendacao[0,i] == 1:
        print(filmes[i])

O chamado
American Pie
